baseURL = 'https://blog.sudoalex.dev/'
languageCode = 'en-us'
title = "Alex's Blog"
theme = "paperMod"


[menus]
[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
[[menus.main]]
    name = 'Archive'
    pageRef = '/archive'
    weight = 20
[[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
[[menus.main]]
    name = 'Search'
    pageRef = '/search'
    weight = 40
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 50


[params]
defaultTheme = "auto"
ShowPostNavLinks = true
ShowCodeCopyButtons = true
author = ["Alex"]
comments = true
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true



[params.homeInfoParams]
Title = "The Blog of Alex"
Content = "A blog about programming, Linux, and other tech stuff."

[[params.socialIcons]]
name = "GitHub"
url= "https://github.com/sudoalx"

[[params.socialIcons]]
name = "Telegram"
url= "https://t.me/sudoalx"

[[params.socialIcons]]
name = "mastodon"
url= "https://mastodon.social/@sudoalex"

[[params.homeInfoParams.buttons]]
name= "Archive"
url= "/archive"

[outputs]
home = [ "HTML", "RSS", "JSON" ]