baseURL = 'https://blog.sudoalex.dev/'
languageCode = 'en-us'
title = "Alex's Blog"
theme = "paperMod"

[params]
defaultTheme = "auto"
ShowPostNavLinks = true
ShowCodeCopyButtons = true
author = ["Alex"]
comments = true
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true


[params.homeInfoParams]
Title = "The Blog of Alex"
Content = "A blog about programming, Linux, and other tech stuff."

[[params.socialIcons]]
name = "GitHub"
url= "https://github.com/sudoalx"

[[params.socialIcons]]
name = "Telegram"
url= "https://t.me/sudoalx"

[[params.socialIcons]]
name = "mastodon"
url= "https://mastodon.social/@sudoalex"


[outputs]
home = [ "HTML", "RSS", "JSON" ]